# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControlMessageModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PythonCoreLib.Models.ServiceType_pb2 as ServiceType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ControlMessageModel.proto',
  package='PythonCoreLib.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x43ontrolMessageModel.proto\x12\x14PythonCoreLib.Models\x1a\x11ServiceType.proto\"u\n\x13\x43ontrolMessageModel\x12\x18\n\x10receiveServiceId\x18\x01 \x01(\t\x12\x36\n\x0bserviceType\x18\x02 \x01(\x0e\x32!.PythonCoreLib.Models.ServiceType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[ServiceType__pb2.DESCRIPTOR,])




_CONTROLMESSAGEMODEL = _descriptor.Descriptor(
  name='ControlMessageModel',
  full_name='PythonCoreLib.Models.ControlMessageModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiveServiceId', full_name='PythonCoreLib.Models.ControlMessageModel.receiveServiceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serviceType', full_name='PythonCoreLib.Models.ControlMessageModel.serviceType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PythonCoreLib.Models.ControlMessageModel.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=187,
)

_CONTROLMESSAGEMODEL.fields_by_name['serviceType'].enum_type = ServiceType__pb2._SERVICETYPE
DESCRIPTOR.message_types_by_name['ControlMessageModel'] = _CONTROLMESSAGEMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlMessageModel = _reflection.GeneratedProtocolMessageType('ControlMessageModel', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLMESSAGEMODEL,
  '__module__' : 'ControlMessageModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLib.Models.ControlMessageModel)
  })
_sym_db.RegisterMessage(ControlMessageModel)


# @@protoc_insertion_point(module_scope)
