# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTopicEnum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageTopicEnum.proto',
  package='PythonCoreLib.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16MessageTopicEnum.proto\x12\x14PythonCoreLib.Models*W\n\x10MessageTopicEnum\x12\x0f\n\x0bTaskControl\x10\x00\x12\x10\n\x0cTaskItemData\x10\x01\x12\x0c\n\x08TaskCalc\x10\x02\x12\x12\n\x0e\x43ontrolMessage\x10\x04\x62\x06proto3')
)

_MESSAGETOPICENUM = _descriptor.EnumDescriptor(
  name='MessageTopicEnum',
  full_name='PythonCoreLib.Models.MessageTopicEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TaskControl', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TaskItemData', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TaskCalc', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ControlMessage', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=48,
  serialized_end=135,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETOPICENUM)

MessageTopicEnum = enum_type_wrapper.EnumTypeWrapper(_MESSAGETOPICENUM)
TaskControl = 0
TaskItemData = 1
TaskCalc = 2
ControlMessage = 4


DESCRIPTOR.enum_types_by_name['MessageTopicEnum'] = _MESSAGETOPICENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
