# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskItemModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskItemModel.proto',
  package='PythonCoreLib.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13TaskItemModel.proto\x12\x14PythonCoreLib.Models\"~\n\rTaskItemModel\x12\x13\n\x0bmajorTaskId\x18\x01 \x01(\t\x12\x11\n\tsubTaskId\x18\x03 \x01(\t\x12\x13\n\x0bsubTaskTime\x18\x05 \x01(\t\x12\x30\n\x08position\x18\x06 \x01(\x0b\x32\x1e.PythonCoreLib.Models.Position\"/\n\x08Position\x12\x11\n\tlongitude\x18\x01 \x01(\x01\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x62\x06proto3')
)




_TASKITEMMODEL = _descriptor.Descriptor(
  name='TaskItemModel',
  full_name='PythonCoreLib.Models.TaskItemModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='majorTaskId', full_name='PythonCoreLib.Models.TaskItemModel.majorTaskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskId', full_name='PythonCoreLib.Models.TaskItemModel.subTaskId', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskTime', full_name='PythonCoreLib.Models.TaskItemModel.subTaskTime', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='PythonCoreLib.Models.TaskItemModel.position', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=171,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='PythonCoreLib.Models.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='PythonCoreLib.Models.Position.longitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='PythonCoreLib.Models.Position.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=220,
)

_TASKITEMMODEL.fields_by_name['position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['TaskItemModel'] = _TASKITEMMODEL
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskItemModel = _reflection.GeneratedProtocolMessageType('TaskItemModel', (_message.Message,), {
  'DESCRIPTOR' : _TASKITEMMODEL,
  '__module__' : 'TaskItemModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLib.Models.TaskItemModel)
  })
_sym_db.RegisterMessage(TaskItemModel)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'TaskItemModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLib.Models.Position)
  })
_sym_db.RegisterMessage(Position)


# @@protoc_insertion_point(module_scope)
