# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskControlModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskControlModel.proto',
  package='PythonCoreLib.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16TaskControlModel.proto\x12\x14PythonCoreLib.Models\"<\n\x10TaskControlModel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\tb\x06proto3')
)




_TASKCONTROLMODEL = _descriptor.Descriptor(
  name='TaskControlModel',
  full_name='PythonCoreLib.Models.TaskControlModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PythonCoreLib.Models.TaskControlModel.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='PythonCoreLib.Models.TaskControlModel.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='PythonCoreLib.Models.TaskControlModel.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['TaskControlModel'] = _TASKCONTROLMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskControlModel = _reflection.GeneratedProtocolMessageType('TaskControlModel', (_message.Message,), {
  'DESCRIPTOR' : _TASKCONTROLMODEL,
  '__module__' : 'TaskControlModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLib.Models.TaskControlModel)
  })
_sym_db.RegisterMessage(TaskControlModel)


# @@protoc_insertion_point(module_scope)
