# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskResultModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskResultModel.proto',
  package='PythonCoreLibs.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15TaskResultModel.proto\x12\x15PythonCoreLibs.Models\"r\n\x0fTaskResultModel\x12\x13\n\x0bmajorTaskId\x18\x01 \x01(\t\x12\x11\n\tsubTaskId\x18\x02 \x01(\t\x12\x13\n\x0bsubTaskTime\x18\x03 \x01(\t\x12\x0f\n\x07isCrack\x18\x04 \x01(\x08\x12\x11\n\tcrackArea\x18\x05 \x01(\x01\x62\x06proto3')
)




_TASKRESULTMODEL = _descriptor.Descriptor(
  name='TaskResultModel',
  full_name='PythonCoreLibs.Models.TaskResultModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='majorTaskId', full_name='PythonCoreLibs.Models.TaskResultModel.majorTaskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskId', full_name='PythonCoreLibs.Models.TaskResultModel.subTaskId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskTime', full_name='PythonCoreLibs.Models.TaskResultModel.subTaskTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCrack', full_name='PythonCoreLibs.Models.TaskResultModel.isCrack', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crackArea', full_name='PythonCoreLibs.Models.TaskResultModel.crackArea', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['TaskResultModel'] = _TASKRESULTMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskResultModel = _reflection.GeneratedProtocolMessageType('TaskResultModel', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESULTMODEL,
  '__module__' : 'TaskResultModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLibs.Models.TaskResultModel)
  })
_sym_db.RegisterMessage(TaskResultModel)


# @@protoc_insertion_point(module_scope)
