# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskModel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TaskModel.proto',
  package='PythonCoreLib.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fTaskModel.proto\x12\x14PythonCoreLib.Models\"\xbf\x01\n\tTaskModel\x12\x13\n\x0bmajorTaskId\x18\x01 \x01(\t\x12\x15\n\rtaksStartTime\x18\x02 \x01(\t\x12\x11\n\tsubTaskId\x18\x03 \x01(\t\x12\x13\n\x0bsubTaskData\x18\x04 \x01(\t\x12\x13\n\x0bsubTaskTime\x18\x05 \x01(\t\x12\x11\n\tlongitude\x18\x06 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\t\x12\x12\n\nresultData\x18\x08 \x01(\t\x12\x10\n\x08resultId\x18\t \x01(\tb\x06proto3')
)




_TASKMODEL = _descriptor.Descriptor(
  name='TaskModel',
  full_name='PythonCoreLib.Models.TaskModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='majorTaskId', full_name='PythonCoreLib.Models.TaskModel.majorTaskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='taksStartTime', full_name='PythonCoreLib.Models.TaskModel.taksStartTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskId', full_name='PythonCoreLib.Models.TaskModel.subTaskId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskData', full_name='PythonCoreLib.Models.TaskModel.subTaskData', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subTaskTime', full_name='PythonCoreLib.Models.TaskModel.subTaskTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='PythonCoreLib.Models.TaskModel.longitude', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='PythonCoreLib.Models.TaskModel.latitude', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultData', full_name='PythonCoreLib.Models.TaskModel.resultData', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultId', full_name='PythonCoreLib.Models.TaskModel.resultId', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['TaskModel'] = _TASKMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskModel = _reflection.GeneratedProtocolMessageType('TaskModel', (_message.Message,), {
  'DESCRIPTOR' : _TASKMODEL,
  '__module__' : 'TaskModel_pb2'
  # @@protoc_insertion_point(class_scope:PythonCoreLib.Models.TaskModel)
  })
_sym_db.RegisterMessage(TaskModel)


# @@protoc_insertion_point(module_scope)
