version: "3.4"
services: 
# the zookeeper server
    zookeeper1:
        image: zookeeper:latest
        expose: 
            - "2181"
        ports:
            - "2181:2181"
        volumes: 
            - "./zk1/conf:/conf"
            - "./zk1/data:/data"
            - "./zk1/datalog:/datalog"
    zookeeper2:
        image: zookeeper:latest
        expose: 
            - "2182"
        ports:
            - "2182:2182"
        volumes: 
            - "./zk2/conf:/conf"
            - "./zk2/data:/data"
            - "./zk2/datalog:/datalog"    
    zookeeper3:
        image: zookeeper:latest
        expose: 
            - "2183"
        ports:
            - "2183:2183"
        volumes: 
            - "./zk3/conf:/conf"
            - "./zk3/data:/data"
            - "./zk3/datalog:/datalog"
# kafka server
    kafka:
        build: 
            context: "./"
            dockerfile: "Dockerfile"
        links: 
            - zookeeper1
            - zookeeper2
            - zookeeper3
        ports: 
            - "9092:9092"
        volumes: 
            - ./kafka:/kafka
# redis server
    redis:
        image: redis:latest
        expose:
            - "6379"
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/usr/local/etc/redis"