# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonCoreLib/Models/proto/TaskModelBase.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PythonCoreLib/Models/proto/TaskModelBase.proto',
  package='Wwbweibo.CrackDetect.Models',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.PythonCoreLib/Models/proto/TaskModelBase.proto\x12\x1bWwbweibo.CrackDetect.Models\"S\n\tTaskModel\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x10\n\x08TaskData\x18\x02 \x01(\x0c\x12\x12\n\nTaslResult\x18\x03 \x01(\x0c\x12\x10\n\x08TaskType\x18\x04 \x01(\tb\x06proto3')
)




_TASKMODEL = _descriptor.Descriptor(
  name='TaskModel',
  full_name='Wwbweibo.CrackDetect.Models.TaskModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='Wwbweibo.CrackDetect.Models.TaskModel.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TaskData', full_name='Wwbweibo.CrackDetect.Models.TaskModel.TaskData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TaslResult', full_name='Wwbweibo.CrackDetect.Models.TaskModel.TaslResult', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TaskType', full_name='Wwbweibo.CrackDetect.Models.TaskModel.TaskType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['TaskModel'] = _TASKMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskModel = _reflection.GeneratedProtocolMessageType('TaskModel', (_message.Message,), {
  'DESCRIPTOR' : _TASKMODEL,
  '__module__' : 'PythonCoreLib.Models.proto.TaskModelBase_pb2'
  # @@protoc_insertion_point(class_scope:Wwbweibo.CrackDetect.Models.TaskModel)
  })
_sym_db.RegisterMessage(TaskModel)


# @@protoc_insertion_point(module_scope)
